"""
Medical knowledge base: ICD-10/CPT codes, denial patterns, insurance policy documents.
Serves as the RAG corpus indexed by BM25Retriever.
"""

from typing import Optional

def _text(*fields) -> str:
    """Flatten fields into a single searchable string."""
    parts = []
    for f in fields:
        if isinstance(f, str):
            parts.append(f)
        elif isinstance(f, list):
            parts.extend(str(x) for x in f)
    return " ".join(parts)


# ── ICD-10 Diagnosis Codes ────────────────────────────────────────────────────

_ICD10 = [
    {
        "id": "icd10_I10",
        "type": "medical_code",
        "code": "I10",
        "title": "Essential (Primary) Hypertension",
        "description": "Chronic elevation of systemic arterial blood pressure with no identifiable underlying cause.",
        "clinical_context": "Most common cardiovascular risk factor; affects ~50% of US adults. Managed with ACE inhibitors, ARBs, thiazide diuretics, or calcium channel blockers.",
        "common_comorbidities": ["E11.9", "E78.5", "I25.10", "I50.9"],
        "common_treatments": ["Lisinopril", "Amlodipine", "Losartan", "Hydrochlorothiazide", "Metoprolol"],
        "denial_risks": "Office visit claims rarely denied. Antihypertensive medications generally covered under formulary tier 1-2. Cardiac imaging may require prior auth if no documented progression.",
        "keywords": ["hypertension", "blood pressure", "HTN", "I10", "essential hypertension", "high blood pressure", "antihypertensive"],
    },
    {
        "id": "icd10_E11_9",
        "type": "medical_code",
        "code": "E11.9",
        "title": "Type 2 Diabetes Mellitus Without Complications",
        "description": "Metabolic disorder characterized by insulin resistance and relative insulin deficiency without documented complications.",
        "clinical_context": "Managed with lifestyle modification and medications (metformin first-line). Requires regular HbA1c monitoring, annual eye and foot exams.",
        "common_comorbidities": ["I10", "E78.5", "E66.9", "N18.3"],
        "common_treatments": ["Metformin", "GLP-1 agonists", "SGLT2 inhibitors", "Insulin", "DPP-4 inhibitors"],
        "denial_risks": "Specialty diabetes medications (GLP-1, SGLT2) often require step therapy (metformin failure documented first) and prior authorization.",
        "keywords": ["diabetes", "type 2 diabetes", "T2DM", "E11", "E11.9", "blood sugar", "glucose", "insulin resistance", "metformin", "hyperglycemia"],
    },
    {
        "id": "icd10_E78_5",
        "type": "medical_code",
        "code": "E78.5",
        "title": "Hyperlipidemia / Dyslipidemia",
        "description": "Abnormal levels of lipids in the bloodstream — elevated LDL, low HDL, or elevated triglycerides.",
        "clinical_context": "Major cardiovascular risk factor. Managed with statins (first-line), fibrates, PCSK9 inhibitors. Annual fasting lipid panel recommended.",
        "common_comorbidities": ["I10", "E11.9", "I25.10", "E66.9"],
        "common_treatments": ["Atorvastatin", "Rosuvastatin", "Simvastatin", "Fenofibrate", "Evolocumab", "Alirocumab"],
        "denial_risks": "High-intensity statin therapy generally covered. PCSK9 inhibitors (evolocumab, alirocumab) require prior auth: must document statin failure or intolerance plus LDL >= 70 mg/dL on maximally tolerated therapy.",
        "keywords": ["dyslipidemia", "hyperlipidemia", "cholesterol", "LDL", "HDL", "triglycerides", "statin", "E78", "E78.5", "lipid panel", "atorvastatin", "rosuvastatin"],
    },
    {
        "id": "icd10_I25_10",
        "type": "medical_code",
        "code": "I25.10",
        "title": "Atherosclerotic Heart Disease (Coronary Artery Disease)",
        "description": "Narrowing of coronary arteries due to atherosclerotic plaque buildup, reducing blood flow to the heart muscle.",
        "clinical_context": "Leading cause of death in the US. Managed with antiplatelet therapy, statins, beta-blockers, ACE inhibitors. May require PCI or CABG for severe cases.",
        "common_comorbidities": ["I10", "E11.9", "E78.5", "I50.9", "I48.91"],
        "common_treatments": ["Aspirin", "Clopidogrel", "Atorvastatin", "Metoprolol", "Lisinopril", "Nitroglycerin"],
        "denial_risks": "Cardiac catheterization and PCI require prior auth in elective settings. Stress testing may require documentation of chest pain symptoms or risk factors.",
        "keywords": ["coronary artery disease", "CAD", "atherosclerosis", "heart disease", "I25", "I25.10", "angina", "myocardial", "cardiac"],
    },
    {
        "id": "icd10_I50_9",
        "type": "medical_code",
        "code": "I50.9",
        "title": "Heart Failure, Unspecified",
        "description": "Cardiac condition where the heart cannot pump sufficient blood to meet the body's needs.",
        "clinical_context": "Managed with diuretics, ACE inhibitors/ARBs/ARNI, beta-blockers, mineralocorticoid antagonists. Ejection fraction determines therapy type (HFrEF vs HFpEF).",
        "common_comorbidities": ["I10", "I48.91", "I25.10", "N18.3"],
        "common_treatments": ["Furosemide", "Sacubitril/Valsartan", "Carvedilol", "Spironolactone", "Dapagliflozin"],
        "denial_risks": "Hospitalizations and advanced therapies (LVAD, transplant workup) require careful documentation of functional class and prior treatment failure.",
        "keywords": ["heart failure", "CHF", "congestive heart failure", "I50", "I50.9", "ejection fraction", "HFrEF", "HFpEF", "cardiac output", "BNP"],
    },
    {
        "id": "icd10_I48_91",
        "type": "medical_code",
        "code": "I48.91",
        "title": "Unspecified Atrial Fibrillation",
        "description": "Irregular and often rapid heart rhythm originating in the atria, increasing stroke risk.",
        "clinical_context": "Anticoagulation to prevent stroke (CHA2DS2-VASc score guides therapy). Rate or rhythm control depending on clinical scenario.",
        "common_comorbidities": ["I10", "I50.9", "I25.10", "Z86.79"],
        "common_treatments": ["Apixaban", "Rivaroxaban", "Warfarin", "Metoprolol", "Diltiazem", "Amiodarone"],
        "denial_risks": "DOACs (apixaban, rivaroxaban) generally covered with prior auth in some plans. Cardioversion requires documentation of duration and anticoagulation status.",
        "keywords": ["atrial fibrillation", "AFib", "AF", "I48", "I48.91", "anticoagulation", "stroke prevention", "arrhythmia", "apixaban"],
    },
    {
        "id": "icd10_J06_9",
        "type": "medical_code",
        "code": "J06.9",
        "title": "Acute Upper Respiratory Infection, Unspecified",
        "description": "Common cold or viral upper respiratory tract infection; typically self-limiting.",
        "clinical_context": "Supportive care. Antibiotics not indicated for viral URI. Watch for complications (otitis, sinusitis, pneumonia).",
        "common_comorbidities": ["J45.909", "J30.9"],
        "common_treatments": ["Supportive care", "Pseudoephedrine", "Guaifenesin", "Acetaminophen"],
        "denial_risks": "Office visit (99213) for URI rarely denied. Antibiotic prescriptions for viral URIs may trigger pharmacy edits.",
        "keywords": ["upper respiratory infection", "URI", "J06", "J06.9", "common cold", "viral", "cough", "runny nose", "Z00.00"],
    },
    {
        "id": "icd10_M17_11",
        "type": "medical_code",
        "code": "M17.11",
        "title": "Primary Osteoarthritis, Right Knee",
        "description": "Degenerative joint disease of the right knee with cartilage breakdown and subchondral bone changes.",
        "clinical_context": "Managed with conservative therapy first (NSAIDs, PT, weight loss, intra-articular injections). Total knee arthroplasty (TKA) indicated when conservative measures fail.",
        "common_comorbidities": ["M79.3", "Z96.641", "E66.9", "M54.5"],
        "common_treatments": ["NSAIDs", "Corticosteroid injection", "Hyaluronic acid injection", "Physical therapy", "TKA (CPT 27447)"],
        "denial_risks": "TKA (CPT 27447) requires documented conservative therapy failure (typically 3+ months PT, NSAIDs). Out-of-network TKA is rarely covered except in emergencies.",
        "keywords": ["osteoarthritis", "knee", "M17", "M17.11", "knee replacement", "arthroplasty", "right knee", "degenerative joint", "TKA", "27447"],
    },
    {
        "id": "icd10_M79_3",
        "type": "medical_code",
        "code": "M79.3",
        "title": "Panniculitis",
        "description": "Inflammation of the subcutaneous fat tissue; can be associated with systemic diseases.",
        "clinical_context": "Diagnosis requires clinical exam and often biopsy. Management varies by type.",
        "common_comorbidities": ["M17.11", "E66.9"],
        "common_treatments": ["NSAIDs", "Corticosteroids", "Wound care"],
        "denial_risks": "Biopsy for panniculitis diagnosis may require prior authorization for advanced imaging. Systemic treatment may require documentation of diagnosis.",
        "keywords": ["panniculitis", "M79.3", "subcutaneous fat", "inflammation", "biopsy"],
    },
    {
        "id": "icd10_Z96_641",
        "type": "medical_code",
        "code": "Z96.641",
        "title": "Presence of Right Artificial Knee Joint",
        "description": "History/status code indicating a previously implanted right total knee prosthesis.",
        "clinical_context": "Used as a secondary code. Patient has undergone TKA previously. Monitor for implant complications, loosening, infection.",
        "common_comorbidities": ["M17.11", "Z87.39"],
        "common_treatments": ["Monitoring", "Revision arthroplasty if needed"],
        "denial_risks": "Revision TKA claims receive heightened scrutiny; require documentation of implant failure, infection, or loosening.",
        "keywords": ["artificial knee", "knee prosthesis", "Z96.641", "knee replacement", "prior TKA", "implant"],
    },
    {
        "id": "icd10_Z87_39",
        "type": "medical_code",
        "code": "Z87.39",
        "title": "Personal History of Other Musculoskeletal Disorders",
        "description": "History code indicating prior musculoskeletal conditions affecting treatment context.",
        "clinical_context": "Secondary/history code. Provides context for current musculoskeletal complaints and treatment decisions.",
        "common_comorbidities": ["M17.11", "M54.5", "Z96.641"],
        "common_treatments": ["Based on current condition"],
        "denial_risks": "History codes alone do not drive claims but provide supporting context for medical necessity.",
        "keywords": ["history musculoskeletal", "Z87.39", "prior condition", "personal history"],
    },
    {
        "id": "icd10_M54_5",
        "type": "medical_code",
        "code": "M54.5",
        "title": "Low Back Pain",
        "description": "Pain in the lumbar region of the spine; may be mechanical, radicular, or referred.",
        "clinical_context": "Most common musculoskeletal complaint. Conservative care first (PT, NSAIDs). Imaging only if red flags present or >4-6 weeks without improvement.",
        "common_comorbidities": ["M17.11", "E66.9", "F32.1"],
        "common_treatments": ["NSAIDs", "Muscle relaxants", "Physical therapy", "Epidural steroid injection", "Surgery for refractory cases"],
        "denial_risks": "Lumbar MRI requires documentation of conservative treatment failure or neurological deficits. Spinal fusion (CPT 22612) requires 6+ months conservative therapy failure.",
        "keywords": ["low back pain", "LBP", "lumbar pain", "M54.5", "back pain", "spine", "lumbar"],
    },
    {
        "id": "icd10_N39_0",
        "type": "medical_code",
        "code": "N39.0",
        "title": "Urinary Tract Infection, Site Not Specified",
        "description": "Bacterial infection of the urinary tract; most commonly E. coli.",
        "clinical_context": "Treated with antibiotics (nitrofurantoin, trimethoprim-sulfamethoxazole, or fluoroquinolones based on culture). Culture and sensitivity guides therapy.",
        "common_comorbidities": ["E11.9", "N18.3"],
        "common_treatments": ["Nitrofurantoin", "Trimethoprim-sulfamethoxazole", "Ciprofloxacin", "Fosfomycin"],
        "denial_risks": "UTI treatment rarely denied. Recurrent UTIs may require documentation for prophylactic antibiotic coverage.",
        "keywords": ["UTI", "urinary tract infection", "N39.0", "bladder infection", "E coli", "antibiotics", "dysuria"],
    },
    {
        "id": "icd10_K21_0",
        "type": "medical_code",
        "code": "K21.0",
        "title": "Gastroesophageal Reflux Disease (GERD) with Esophagitis",
        "description": "Chronic acid reflux causing esophageal inflammation.",
        "clinical_context": "Managed with PPIs (first-line), H2 blockers, lifestyle modification. EGD for diagnosis confirmation or when alarm symptoms present.",
        "common_comorbidities": ["K22.0", "E66.9"],
        "common_treatments": ["Omeprazole", "Pantoprazole", "Famotidine", "Ranitidine"],
        "denial_risks": "Long-term PPI use may require step therapy documentation. EGD (CPT 43239) for GERD requires alarm symptoms (dysphagia, weight loss, bleeding) or treatment failure.",
        "keywords": ["GERD", "reflux", "K21", "K21.0", "acid reflux", "esophagitis", "PPI", "omeprazole", "heartburn"],
    },
    {
        "id": "icd10_F32_1",
        "type": "medical_code",
        "code": "F32.1",
        "title": "Major Depressive Disorder, Moderate",
        "description": "Clinical depression with persistent depressed mood, anhedonia, and functional impairment.",
        "clinical_context": "Treated with SSRIs/SNRIs (first-line), psychotherapy, or combination. PHQ-9 score 10-19 indicates moderate severity.",
        "common_comorbidities": ["F41.1", "M54.5", "E11.9"],
        "common_treatments": ["Sertraline", "Escitalopram", "Bupropion", "Venlafaxine", "Cognitive behavioral therapy"],
        "denial_risks": "Mental health parity laws require coverage equivalent to medical benefits. Atypical antipsychotics as adjuncts may require step therapy documentation.",
        "keywords": ["depression", "major depressive disorder", "MDD", "F32", "F32.1", "SSRI", "antidepressant", "PHQ-9", "mental health"],
    },
    {
        "id": "icd10_J45_909",
        "type": "medical_code",
        "code": "J45.909",
        "title": "Unspecified Asthma, Uncomplicated",
        "description": "Chronic inflammatory airway disease with reversible airflow obstruction.",
        "clinical_context": "Step-up therapy based on symptom severity. Short-acting beta-agonists (SABA) for rescue; inhaled corticosteroids (ICS) for controller therapy.",
        "common_comorbidities": ["J30.9", "J06.9", "E66.9"],
        "common_treatments": ["Albuterol", "Fluticasone", "Budesonide", "Montelukast", "Salmeterol", "Dupilumab"],
        "denial_risks": "Biologic therapies (dupilumab, mepolizumab) for severe asthma require prior auth with documented: eosinophil count, ICS failure, pulmonologist attestation.",
        "keywords": ["asthma", "J45", "J45.909", "SABA", "ICS", "albuterol", "bronchospasm", "wheezing", "inhaler", "peak flow"],
    },
    {
        "id": "icd10_E66_9",
        "type": "medical_code",
        "code": "E66.9",
        "title": "Obesity, Unspecified",
        "description": "BMI >= 30 kg/m2; associated with numerous comorbidities.",
        "clinical_context": "Managed with lifestyle modification, pharmacotherapy, and bariatric surgery. BMI >=40 or >=35 with comorbidities typically threshold for bariatric surgery consideration.",
        "common_comorbidities": ["E11.9", "I10", "M17.11", "J45.909", "I50.9"],
        "common_treatments": ["Semaglutide", "Phentermine-topiramate", "Orlistat", "Bariatric surgery", "Nutritional counseling"],
        "denial_risks": "GLP-1 agonists for weight loss require prior auth; must document BMI threshold and failed prior weight loss interventions. Bariatric surgery requires 6-month documented supervised weight management program.",
        "keywords": ["obesity", "E66", "E66.9", "BMI", "overweight", "weight loss", "bariatric", "semaglutide", "GLP-1", "Ozempic"],
    },
    {
        "id": "icd10_Z00_00",
        "type": "medical_code",
        "code": "Z00.00",
        "title": "General Adult Medical Examination Without Abnormal Findings",
        "description": "Routine preventive health check in an adult with no identified abnormal findings.",
        "clinical_context": "Annual wellness visit. Preventive services under ACA must be covered at no cost-sharing for most plans.",
        "common_comorbidities": [],
        "common_treatments": ["Routine screenings", "Immunizations", "Counseling"],
        "denial_risks": "Preventive visits coded Z00.00 should not have cost-sharing under ACA. Denial may indicate coding issue — separate problem-oriented services should use E/M codes.",
        "keywords": ["preventive", "annual exam", "Z00.00", "wellness visit", "checkup", "physical", "screening", "routine"],
    },
]

# ── CPT Procedure Codes ───────────────────────────────────────────────────────

_CPT = [
    {
        "id": "cpt_99213",
        "type": "medical_code",
        "code": "99213",
        "title": "Office Visit, Established Patient — Level 3 (Moderate Complexity)",
        "description": "Outpatient office visit for an established patient requiring moderate medical decision making (2 stable chronic conditions or 1 new problem).",
        "typical_diagnoses": ["I10", "E11.9", "J06.9", "Z00.00"],
        "usual_and_customary_range": "$150–$250",
        "denial_risks": "Rarely denied on its own. Unbundling from same-day procedures may trigger review. Ensure medical necessity documentation matches complexity level.",
        "keywords": ["99213", "office visit", "established patient", "level 3", "moderate", "outpatient", "E/M"],
    },
    {
        "id": "cpt_99214",
        "type": "medical_code",
        "code": "99214",
        "title": "Office Visit, Established Patient — Level 4 (High Complexity)",
        "description": "Office visit requiring high medical decision making (3+ stable chronic conditions, or 1 undiagnosed problem, or acute illness with systemic symptoms).",
        "typical_diagnoses": ["I10", "E11.9", "I25.10", "I50.9"],
        "usual_and_customary_range": "$250–$450",
        "denial_risks": "Documentation must support high complexity MDM. Audits may downcode to 99213 if documentation is insufficient.",
        "keywords": ["99214", "office visit", "level 4", "high complexity", "established patient", "E/M"],
    },
    {
        "id": "cpt_27447",
        "type": "medical_code",
        "code": "27447",
        "title": "Total Knee Arthroplasty (TKA)",
        "description": "Surgical replacement of the knee joint with a prosthetic implant. Indicated for end-stage osteoarthritis or other severe knee pathology.",
        "typical_diagnoses": ["M17.11", "M17.12", "M19.011"],
        "usual_and_customary_range": "$30,000–$55,000 (facility + surgeon + anesthesia)",
        "denial_risks": "REQUIRES PRIOR AUTHORIZATION in nearly all plans. Common denial reasons: (1) insufficient conservative therapy documentation, (2) out-of-network facility, (3) medical necessity documentation absent. Must document: X-ray evidence, 3+ months conservative therapy failure, functional limitation.",
        "preauth_required": "Yes — prior authorization mandatory for all elective TKA",
        "keywords": ["TKA", "total knee arthroplasty", "27447", "knee replacement", "knee surgery", "orthopedic", "arthroplasty"],
    },
    {
        "id": "cpt_93000",
        "type": "medical_code",
        "code": "93000",
        "title": "Electrocardiography (ECG/EKG) with Interpretation",
        "description": "12-lead electrocardiogram recording and professional interpretation. Used to evaluate cardiac rhythm, ischemia, and conduction abnormalities.",
        "typical_diagnoses": ["I10", "I48.91", "I25.10", "I50.9"],
        "usual_and_customary_range": "$50–$150",
        "denial_risks": "Generally covered with cardiac diagnosis. Denial risk if bundled same-day with a higher-level evaluation (may be included in the E/M). Standalone ECG for screening without symptoms may be denied.",
        "keywords": ["ECG", "EKG", "electrocardiogram", "93000", "heart rhythm", "cardiac monitoring"],
    },
    {
        "id": "cpt_85025",
        "type": "medical_code",
        "code": "85025",
        "title": "Complete Blood Count (CBC) with Automated Differential",
        "description": "Laboratory panel measuring red blood cells, white blood cells, platelets, hemoglobin, and hematocrit with white cell differential.",
        "typical_diagnoses": ["D64.9", "J06.9", "I10", "E11.9"],
        "usual_and_customary_range": "$25–$75",
        "denial_risks": "Rarely denied when ordered with clinical indication. Serial CBCs without clinical change may trigger medical necessity review.",
        "keywords": ["CBC", "complete blood count", "85025", "hemoglobin", "white blood cells", "differential", "labs"],
    },
    {
        "id": "cpt_80053",
        "type": "medical_code",
        "code": "80053",
        "title": "Comprehensive Metabolic Panel (CMP)",
        "description": "14-test laboratory panel: glucose, calcium, sodium, potassium, CO2, chloride, BUN, creatinine, albumin, total protein, ALP, ALT, AST, bilirubin.",
        "typical_diagnoses": ["E11.9", "I10", "I50.9", "K21.0"],
        "usual_and_customary_range": "$30–$90",
        "denial_risks": "Rarely denied with chronic disease management. May be bundled with other panels — avoid duplicate ordering.",
        "keywords": ["CMP", "comprehensive metabolic panel", "80053", "BMP", "kidney function", "liver function", "electrolytes", "creatinine", "BUN"],
    },
    {
        "id": "cpt_71046",
        "type": "medical_code",
        "code": "71046",
        "title": "Chest X-Ray, 2 Views",
        "description": "Standard PA and lateral chest radiographs evaluating lungs, heart, mediastinum, and bony thorax.",
        "typical_diagnoses": ["J06.9", "J45.909", "I50.9", "J18.9"],
        "usual_and_customary_range": "$100–$300",
        "denial_risks": "Covered with acute respiratory or cardiac symptoms. Routine screening CXR without symptoms or clinical indication may be denied.",
        "keywords": ["chest x-ray", "CXR", "71046", "chest radiograph", "PA lateral", "lung", "pulmonary"],
    },
    {
        "id": "cpt_70553",
        "type": "medical_code",
        "code": "70553",
        "title": "MRI Brain with Contrast",
        "description": "Magnetic resonance imaging of the brain with gadolinium contrast enhancement. Used for tumor evaluation, inflammation, and vascular lesions.",
        "typical_diagnoses": ["G40.909", "I63.9", "C71.9"],
        "usual_and_customary_range": "$1,200–$3,500",
        "denial_risks": "REQUIRES PRIOR AUTHORIZATION at most plans. Must document: clinical symptoms justifying contrast (e.g., known/suspected neoplasm, MS, abscess). Non-contrast MRI (CPT 70551) has lower PA threshold.",
        "preauth_required": "Yes — most plans require prior auth for brain MRI with contrast",
        "keywords": ["MRI brain", "70553", "brain imaging", "contrast MRI", "gadolinium", "neuroimaging", "brain scan"],
    },
    {
        "id": "cpt_43239",
        "type": "medical_code",
        "code": "43239",
        "title": "Upper GI Endoscopy (EGD) with Biopsy",
        "description": "Esophagogastroduodenoscopy with tissue biopsy. Evaluates esophagus, stomach, and duodenum; used for GERD refractory to treatment, Barrett's surveillance, dysphagia.",
        "typical_diagnoses": ["K21.0", "K22.0", "K92.1"],
        "usual_and_customary_range": "$1,500–$4,000",
        "denial_risks": "Requires prior auth at many plans. Must document: failed PPI trial (>8 weeks), alarm symptoms (dysphagia, weight loss, GI bleeding, iron-deficiency anemia), or surveillance indication.",
        "keywords": ["EGD", "endoscopy", "43239", "upper GI", "esophagoscopy", "biopsy", "Barrett's", "GERD evaluation", "scope"],
    },
    {
        "id": "cpt_45378",
        "type": "medical_code",
        "code": "45378",
        "title": "Colonoscopy, Diagnostic",
        "description": "Flexible fiberoptic colonoscopy without biopsy or polyp removal. Evaluates the entire colon for neoplasia, inflammation, or bleeding.",
        "typical_diagnoses": ["C18.9", "K57.30", "D12.6"],
        "usual_and_customary_range": "$2,000–$6,000",
        "denial_risks": "Preventive colonoscopy (Z12.11) covered at no cost-sharing under ACA. Diagnostic colonoscopy for symptoms may have cost-sharing. Frequency limits apply (typically every 10 years for average-risk patients).",
        "keywords": ["colonoscopy", "45378", "colon cancer screening", "colorectal", "flexible sigmoidoscopy", "colon scope", "polyp"],
    },
    {
        "id": "cpt_22612",
        "type": "medical_code",
        "code": "22612",
        "title": "Lumbar Arthrodesis (Spinal Fusion), Posterior",
        "description": "Surgical fusion of lumbar vertebrae via posterior approach. Indicated for instability, severe stenosis, or refractory radiculopathy.",
        "typical_diagnoses": ["M54.5", "M47.816", "M51.16"],
        "usual_and_customary_range": "$60,000–$120,000",
        "denial_risks": "REQUIRES PRIOR AUTHORIZATION — one of the most scrutinized procedures. Requirements: documented 6+ months conservative therapy failure (PT, injections, medications), MRI evidence of pathology, neurological deficit or severe functional limitation, and second opinion in many plans.",
        "preauth_required": "Yes — mandatory, among highest-scrutiny surgical procedures",
        "keywords": ["spinal fusion", "22612", "lumbar fusion", "back surgery", "arthrodesis", "vertebral fusion", "spine surgery"],
    },
    {
        "id": "cpt_29827",
        "type": "medical_code",
        "code": "29827",
        "title": "Arthroscopy, Shoulder — Rotator Cuff Repair",
        "description": "Minimally invasive shoulder surgery to repair torn rotator cuff tendons.",
        "typical_diagnoses": ["M75.100", "M75.120"],
        "usual_and_customary_range": "$15,000–$35,000",
        "denial_risks": "REQUIRES PRIOR AUTHORIZATION. Must document: MRI confirming tear, failed conservative therapy (typically 6–12 weeks PT + injections), functional limitation affecting activities of daily living.",
        "preauth_required": "Yes",
        "keywords": ["rotator cuff", "29827", "shoulder surgery", "arthroscopy shoulder", "rotator cuff repair", "shoulder scope"],
    },
]

# ── Denial Patterns ───────────────────────────────────────────────────────────

_DENIAL_PATTERNS = [
    {
        "id": "denial_no_preauth_surgical",
        "type": "denial_pattern",
        "title": "Missing Prior Authorization — Surgical Procedure",
        "trigger_cpt": ["27447", "22612", "23472", "29827", "70553", "43239"],
        "description": "Services requiring prior authorization were rendered without obtaining approval in advance.",
        "policy_citation": "Standard policy section 4.2 — Prior Authorization Requirements for Elective Surgical and Invasive Procedures",
        "resolution": "Services without prior auth are generally non-covered per contract terms.",
        "appeal_template": "File Level 1 appeal within 180 days. Include: (1) letter of medical necessity from treating physician, (2) all relevant clinical documentation (imaging, prior treatment records), (3) documentation of why emergent circumstances prevented prior auth if applicable, (4) completed appeal form CMS-20031.",
        "success_factors": "Appeals succeed most often when: true medical emergency occurred, patient relied on incorrect prior auth information from insurer, or clerical/administrative error by plan can be demonstrated.",
        "keywords": ["prior authorization", "prior auth", "preauth", "PA required", "no authorization", "missing authorization", "surgical", "authorization denied"],
    },
    {
        "id": "denial_no_preauth_imaging",
        "type": "denial_pattern",
        "title": "Missing Prior Authorization — Advanced Imaging",
        "trigger_cpt": ["70553", "70551", "73721", "72148", "74177"],
        "description": "Advanced imaging (CT, MRI, PET) performed without required prior authorization.",
        "policy_citation": "Radiology management program — prior authorization required for advanced imaging per clinical appropriateness criteria.",
        "resolution": "Denied without PA; retrospective review may approve if clinical criteria met.",
        "appeal_template": "File within 180 days. Include: ordering physician clinical rationale, prior treatment and symptom documentation, evidence that clinical appropriateness criteria are met (e.g., ACR guidelines).",
        "success_factors": "Provide complete clinical history supporting medical necessity. Reference ACR Appropriateness Criteria for the ordered study.",
        "keywords": ["imaging", "prior auth MRI", "CT authorization", "advanced imaging", "radiology", "MRI denied", "prior auth imaging"],
    },
    {
        "id": "denial_out_of_network",
        "type": "denial_pattern",
        "title": "Out-of-Network Provider",
        "trigger_conditions": ["out_of_network flag"],
        "description": "Services were rendered by a provider not contracted with the patient's insurance network.",
        "policy_citation": "Network participation requirements — coverage limited to in-network providers except for emergency services.",
        "resolution": "Non-emergency OON services typically covered at OON benefit tier with higher cost-sharing, or denied entirely for HMO plans.",
        "appeal_template": "File within 180 days. Include: (1) documentation that no in-network provider was available within reasonable distance or time, (2) evidence of medical necessity requiring this specific provider's expertise, (3) any continuity of care circumstances (established care with this provider), (4) gap-in-network exception request form.",
        "success_factors": "Gap-in-network exceptions succeed when: specialty not available in-network, continuity of care for ongoing treatment, or geographical access limitations documented.",
        "keywords": ["out of network", "OON", "out-of-network", "non-participating provider", "network", "not contracted", "balance billing"],
    },
    {
        "id": "denial_experimental",
        "type": "denial_pattern",
        "title": "Experimental or Investigational Treatment",
        "trigger_conditions": ["experimental_treatment flag"],
        "description": "Treatment is classified as experimental, investigational, or not medically recognized.",
        "policy_citation": "Coverage exclusions — experimental/investigational services defined as lacking sufficient clinical evidence or not FDA approved for the indication.",
        "resolution": "Generally non-covered; may qualify for clinical trial coverage under ACA requirements.",
        "appeal_template": "File within 180 days. Include: (1) peer-reviewed literature supporting clinical efficacy, (2) FDA approval status or breakthrough therapy designation, (3) clinical trial enrollment information if applicable, (4) treating physician's detailed letter of medical necessity citing evidence base.",
        "success_factors": "Appeals strongest when: FDA approval exists for the indication, multiple clinical guidelines endorse the therapy, or significant peer-reviewed evidence available.",
        "keywords": ["experimental", "investigational", "not approved", "unproven", "experimental treatment", "clinical trial", "off-label"],
    },
    {
        "id": "denial_medical_necessity",
        "type": "denial_pattern",
        "title": "Medical Necessity Not Established",
        "trigger_conditions": ["high complexity", "specialty services"],
        "description": "The service did not meet the plan's criteria for medical necessity based on submitted documentation.",
        "policy_citation": "Coverage requirement — services must be medically necessary, meaning consistent with evidence-based medicine, appropriate for the diagnosis, and not primarily for patient convenience.",
        "resolution": "Additional clinical documentation may satisfy necessity criteria upon appeal.",
        "appeal_template": "File within 180 days. Include: (1) detailed clinical notes documenting symptom severity and functional impact, (2) evidence-based clinical guidelines supporting the service (e.g., ACC/AHA, AAOS guidelines), (3) documentation of prior conservative treatment failure, (4) statement of how this service improves patient outcomes.",
        "success_factors": "Success rate highest when treating physician provides detailed narrative tying clinical presentation to evidence-based indications. Use plan's specific clinical criteria if available.",
        "keywords": ["medical necessity", "not medically necessary", "necessity not met", "clinical criteria", "not indicated", "medically appropriate"],
    },
    {
        "id": "denial_duplicate_claim",
        "type": "denial_pattern",
        "title": "Duplicate Claim",
        "trigger_conditions": ["same patient", "same date", "same procedure"],
        "description": "Claim appears to be a duplicate of a previously submitted or processed claim.",
        "policy_citation": "Claims processing — duplicate submissions are rejected to prevent overpayment.",
        "resolution": "If genuinely duplicate, no action needed. If incorrectly flagged, correct with claim resubmission with reference number.",
        "appeal_template": "File a corrected claim or appeal within 180 days. Include: (1) reference to original claim number, (2) explanation of why this is a separate, distinct service, (3) supporting documentation showing different date, service, or provider if applicable.",
        "success_factors": "Straightforward resolution if the claim was incorrectly identified as duplicate — provide original claim number and detailed explanation.",
        "keywords": ["duplicate", "duplicate claim", "already processed", "resubmission", "previously billed"],
    },
    {
        "id": "denial_non_covered",
        "type": "denial_pattern",
        "title": "Non-Covered Service or Exclusion",
        "trigger_conditions": ["exclusions", "benefit limit"],
        "description": "The requested service is specifically excluded from coverage under the patient's plan.",
        "policy_citation": "Plan exclusions — specific services may be excluded from benefits (e.g., cosmetic procedures, certain fertility treatments, experimental therapies).",
        "resolution": "Non-covered exclusions are not appealable on clinical grounds; only if miscategorized.",
        "appeal_template": "File within 180 days if you believe the service was miscategorized. Include: (1) documentation that service is therapeutic (not cosmetic/elective), (2) ICD-10 codes showing medical basis, (3) clinical notes establishing medical necessity.",
        "success_factors": "Best success when a 'cosmetic' procedure has a documented medical indication (e.g., reconstructive surgery after trauma).",
        "keywords": ["non-covered", "excluded", "exclusion", "not a covered benefit", "not covered", "benefit limit exceeded"],
    },
    {
        "id": "denial_late_filing",
        "type": "denial_pattern",
        "title": "Late Filing — Timely Filing Limit Exceeded",
        "trigger_conditions": ["filing deadline"],
        "description": "Claim was submitted after the plan's timely filing deadline (typically 90–365 days from date of service).",
        "policy_citation": "Timely filing requirements vary by plan: Medicare (12 months), most commercial plans (90–180 days from DOS).",
        "resolution": "Very difficult to reverse — exceptions only for plan error, patient incapacity, or third-party documentation unavailability.",
        "appeal_template": "File immediately. Include: (1) proof of timely original submission (clearinghouse confirmation), (2) documentation of any circumstances preventing timely filing (e.g., coordination of benefits delay, patient incapacity), (3) evidence of plan error if applicable.",
        "success_factors": "Appeals succeed primarily when provider can show original timely submission with electronic confirmation, or when delay was caused by plan's own actions (e.g., incorrect plan information given to patient).",
        "keywords": ["late filing", "timely filing", "filing limit", "deadline", "time limit exceeded", "late claim"],
    },
    {
        "id": "denial_cob",
        "type": "denial_pattern",
        "title": "Coordination of Benefits — Other Insurance Primary",
        "trigger_conditions": ["multiple insurers", "COB"],
        "description": "Patient has multiple insurance coverages; the billed plan is secondary and requires primary carrier's EOB first.",
        "policy_citation": "COB rules — when patient has multiple plans, birthday rule or other COB criteria determine primary vs secondary payer.",
        "resolution": "Submit to primary carrier first; attach primary carrier's EOB to secondary claim.",
        "appeal_template": "Resubmit with: (1) primary carrier's Explanation of Benefits (EOB), (2) corrected COB information, (3) documentation of which plan is primary per COB rules.",
        "success_factors": "Usually resolved administratively upon resubmission with primary EOB — not a true denial in most cases.",
        "keywords": ["COB", "coordination of benefits", "other insurance", "primary payer", "secondary insurance", "EOB required", "birthday rule"],
    },
]

# ── Insurance Policy Documents ────────────────────────────────────────────────

_INSURANCE_POLICIES = [
    {
        "id": "policy_medicaid_ca",
        "type": "insurance_policy",
        "plan": "Medicaid (Medi-Cal)",
        "state": "CA",
        "title": "California Medicaid (Medi-Cal) — Eligibility and Coverage",
        "description": "Medi-Cal provides free or low-cost health coverage to Californians who meet income eligibility requirements.",
        "eligibility_rules": "Adults: income at or below 138% of the Federal Poverty Level (~$20,120 for an individual in 2024, ~$41,400 for a family of 4). No asset test for most eligibility categories. Available year-round with no enrollment period.",
        "coverage_highlights": "Comprehensive coverage including doctor visits, hospital care, mental health, dental, vision, prescriptions, and long-term care. Very low or no out-of-pocket costs.",
        "enrollment": "Apply any time at Covered California or county social services. No open enrollment period — continuous enrollment opportunity.",
        "key_consideration": "If income fluctuates above 138% FPL, patient loses Medicaid eligibility and gains a Special Enrollment Period for ACA Marketplace. Transition planning is critical.",
        "keywords": ["medicaid", "medi-cal", "california", "CA", "low income", "FPL", "138 percent", "free coverage", "Covered California"],
    },
    {
        "id": "policy_medicaid_tx",
        "type": "insurance_policy",
        "plan": "Medicaid",
        "state": "TX",
        "title": "Texas Medicaid — Eligibility and Coverage",
        "description": "Texas Medicaid provides coverage primarily for children, pregnant women, the elderly, and people with disabilities. Texas has not expanded Medicaid under the ACA.",
        "eligibility_rules": "Adults without children generally NOT eligible regardless of income. Parents with children: income below ~18% FPL. Pregnant women: income below 198% FPL. Children (CHIP): income below 209% FPL.",
        "coverage_highlights": "Covers core medical services for eligible groups. Limited adult eligibility compared to expansion states.",
        "enrollment": "Apply through Texas Health and Human Services. No open enrollment restriction for eligible categories.",
        "key_consideration": "Working-age adults without disabilities or dependents in Texas face a coverage gap — ineligible for Medicaid but may not qualify for ACA subsidies without minimum income threshold (~100% FPL).",
        "keywords": ["medicaid", "texas", "TX", "CHIP", "non-expansion", "coverage gap", "Texas medicaid", "children medicaid"],
    },
    {
        "id": "policy_medicare",
        "type": "insurance_policy",
        "plan": "Medicare Parts A & B",
        "state": "Federal",
        "title": "Medicare Parts A & B — Federal Health Insurance for Seniors",
        "description": "Federal health insurance program for people 65 and older, and certain younger individuals with disabilities or end-stage renal disease.",
        "eligibility_rules": "Age 65+ (most common). Under 65: 24 months after Social Security Disability (SSDI) approval, or with ESRD or ALS. US citizen or permanent resident with 10+ years of work credits for premium-free Part A.",
        "coverage_highlights": "Part A: hospital inpatient, skilled nursing facility, hospice, limited home health. Part B: outpatient medical services, preventive care, durable medical equipment, physician visits. No dental, vision, or hearing in original Medicare.",
        "costs": "Part A: generally no premium if sufficient work credits. Part B: 2024 standard premium ~$174.70/month. Both have deductibles and 20% coinsurance for Part B services.",
        "enrollment": "Initial Enrollment Period: 7-month window around 65th birthday. Late enrollment penalty if delayed without qualifying coverage.",
        "key_consideration": "Medicare does not cap out-of-pocket costs in original Medicare; consider Medicare Supplement (Medigap) or Medicare Advantage for additional protection.",
        "keywords": ["medicare", "Medicare Part A", "Medicare Part B", "seniors", "65 years", "disability", "ESRD", "federal", "CMS", "hospital insurance"],
    },
    {
        "id": "policy_aca_subsidized",
        "type": "insurance_policy",
        "plan": "ACA Marketplace — Subsidized Tier",
        "state": "Federal",
        "title": "ACA Health Insurance Marketplace — Premium Tax Credit (Subsidized)",
        "description": "Health insurance plans sold through the Affordable Care Act Marketplace with income-based premium subsidies.",
        "eligibility_rules": "Income between 100%–400% FPL for traditional subsidies; extended subsidy eligibility up to any income under current law. Must not have access to affordable employer-sponsored insurance or Medicare/Medicaid.",
        "coverage_highlights": "All essential health benefits required: preventive care, ER, inpatient, maternity, mental health, prescriptions, lab services, pediatric care. Metal tiers: Bronze (lowest premium, highest cost-sharing) through Platinum.",
        "costs": "Premium after tax credits varies by income and tier. Cost-sharing reductions (CSR) available for Silver plans at 100–250% FPL — reduces deductibles and copays significantly.",
        "enrollment": "Open Enrollment: November 1 – January 15. Special Enrollment Period triggered by qualifying events (job loss, marriage, birth, Medicaid loss).",
        "key_consideration": "Silver plans + CSR is often the best value for patients at 100–250% FPL. Premium tax credits are reconciled at tax filing — income changes during the year must be reported.",
        "keywords": ["ACA", "marketplace", "subsidized", "premium tax credit", "PTC", "affordable care act", "health exchange", "open enrollment", "silver plan", "bronze plan", "CSR"],
    },
    {
        "id": "policy_aca_full_price",
        "type": "insurance_policy",
        "plan": "ACA Marketplace — Full Price",
        "state": "Federal",
        "title": "ACA Health Insurance Marketplace — Full Price (Above Subsidy Threshold)",
        "description": "ACA-compliant marketplace plans for individuals with income above the subsidy threshold or those who prefer marketplace coverage without tax credit.",
        "eligibility_rules": "Open to all legal US residents. Subsidies phase out at higher incomes but plans remain available at full price.",
        "coverage_highlights": "Same essential health benefit requirements as subsidized plans. Comprehensive coverage guaranteed regardless of pre-existing conditions.",
        "costs": "Full unsubsidized premium varies by plan, age, and location — typically $400–$900+/month for an individual.",
        "enrollment": "Same Open Enrollment and SEP rules as subsidized marketplace.",
        "key_consideration": "At higher income levels, employer-sponsored insurance or short-term health plans may be more cost-effective than full-price marketplace.",
        "keywords": ["ACA", "marketplace", "full price", "unsubsidized", "above threshold", "health exchange", "comprehensive coverage"],
    },
    {
        "id": "policy_chip",
        "type": "insurance_policy",
        "plan": "CHIP",
        "state": "Federal",
        "title": "Children's Health Insurance Program (CHIP)",
        "description": "Provides low-cost health coverage to children in families that earn too much for Medicaid but cannot afford private insurance.",
        "eligibility_rules": "Children under 19 in families at or below 200–300% FPL (varies by state). Most states also cover pregnant women. No coverage for adults without children.",
        "coverage_highlights": "Comprehensive coverage: doctor visits, hospital care, prescriptions, dental, vision, mental health, preventive care. Very low premiums (often $0–$50/month) and minimal cost-sharing.",
        "enrollment": "Apply any time through state Medicaid/CHIP agency. No open enrollment restriction.",
        "key_consideration": "CHIP covers dental and vision which Medicaid may not fully cover in all states. Enroll children separately from parents if parents qualify for Medicaid — CHIP and Medicaid can cover different family members simultaneously.",
        "keywords": ["CHIP", "children", "child health", "kids", "SCHIP", "children's insurance", "pediatric", "dependents", "under 19"],
    },
    {
        "id": "policy_esi",
        "type": "insurance_policy",
        "plan": "Employer-Sponsored Insurance (ESI)",
        "state": "General",
        "title": "Employer-Sponsored Health Insurance (ESI)",
        "description": "Health insurance provided through an employer, typically with employer contributing to premium costs.",
        "eligibility_rules": "Available to employees working sufficient hours (typically 30+ hours/week for ACA compliance). Employers with 50+ full-time employees required to offer coverage.",
        "coverage_highlights": "Coverage varies significantly by employer plan. Generally covers essential health benefits. May include dental and vision add-ons.",
        "costs": "Employer typically covers 50–80% of premium. Employee share deducted pre-tax from paycheck. Average employee contribution ~$6,000/year for family coverage.",
        "enrollment": "During new hire enrollment window or annual open enrollment. Special enrollment upon qualifying life events.",
        "key_consideration": "ESI is usually the best-value option when available — employer contributions effectively subsidize coverage more than ACA tax credits for most working households. COBRA allows continuation of ESI for 18–36 months after job loss at full premium cost.",
        "keywords": ["employer insurance", "ESI", "employer sponsored", "group health", "work insurance", "W-2", "group coverage", "COBRA", "benefits"],
    },
    {
        "id": "policy_hdhp_hsa",
        "type": "insurance_policy",
        "plan": "HDHP + HSA",
        "state": "General",
        "title": "High-Deductible Health Plan (HDHP) with Health Savings Account (HSA)",
        "description": "Lower-premium health plan with higher deductible paired with a tax-advantaged HSA for medical expenses.",
        "eligibility_rules": "Available as employer or marketplace plan. HSA eligibility requires HDHP enrollment and no other disqualifying coverage. 2024 HDHP threshold: deductible ≥$1,600 individual/$3,200 family.",
        "coverage_highlights": "Lower premiums than traditional plans. Preventive care covered before deductible. All other services apply toward deductible first.",
        "costs": "HSA contributions (2024): $4,150 individual/$8,300 family. Contributions tax-deductible; earnings tax-free; withdrawals for qualified medical expenses tax-free. Triple tax advantage.",
        "key_consideration": "HDHP + HSA is most advantageous for healthy, higher-income individuals who can afford to fund the HSA and withstand higher out-of-pocket costs before the deductible is met. Poor choice for patients with chronic conditions requiring frequent care.",
        "keywords": ["HDHP", "HSA", "high deductible", "health savings account", "triple tax", "tax-advantaged", "lower premium", "healthy", "high earner"],
    },
]

# ── Build corpus with searchable _text field ──────────────────────────────────

def _build_corpus() -> list[dict]:
    corpus = []
    for docs in [_ICD10, _CPT, _DENIAL_PATTERNS, _INSURANCE_POLICIES]:
        for doc in docs:
            d = dict(doc)
            # Concatenate all string/list fields for BM25 indexing
            parts = []
            for k, v in d.items():
                if k in ("id", "type"):
                    continue
                if isinstance(v, str):
                    parts.append(v)
                elif isinstance(v, list):
                    parts.extend(str(x) for x in v)
            d["_text"] = " ".join(parts)
            corpus.append(d)
    return corpus


CORPUS: list[dict] = _build_corpus()


def get_document(doc_id: str) -> Optional[dict]:
    """Look up a document by ID."""
    return next((d for d in CORPUS if d["id"] == doc_id), None)
