// ── Clinical knowledge, loaded from primary public sources ──────────────────
// Server only. Every lookup here reads a build artifact generated by
// scripts/build_knowledge/build.py from CDC/NCHS, CMS, AHRQ, and NLM data.
// Nothing in this module is hand written clinical content.
//
//   icd10cm.json.gz      ICD 10 CM FY2026 tabular: code -> [billable, description]
//   icd10index.json.gz   ICD 10 CM FY2026 alphabetic index: term -> candidate codes
//   ccsr.json.gz         AHRQ CCSR v2025-1: code -> clinical category
//   pfs.json.gz          CMS PFS rvu26a + CLFS 2026 Q1: code -> [payment, status]
//   meds.json.gz         RxNorm prescribable content: ingredient/brand vocabulary
//   readmissions.json    CMS published 30 day readmission rates + measure cohorts

import fs from 'fs'
import path from 'path'
import zlib from 'zlib'

function loadGz<T>(name: string): T {
  const p = path.join(process.cwd(), 'data', name)
  return JSON.parse(zlib.gunzipSync(fs.readFileSync(p)).toString('utf-8')) as T
}

type IcdTab = Record<string, [number, string]>
type IcdIndex = Record<string, string[]>
type Ccsr = { map: Record<string, string>; categories: Record<string, string> }
type Pfs = { cf: number; pay: Record<string, [number, string] | [number, string, string]> }

let _tab: IcdTab | null = null
let _index: IcdIndex | null = null
let _ccsr: Ccsr | null = null
let _pfs: Pfs | null = null
let _meds: Record<string, string> | null = null
let _tokenIndex: Map<string, number[]> | null = null
let _terms: { term: string; codes: string[] }[] | null = null

const tab = () => (_tab ??= loadGz<IcdTab>('icd10cm.json.gz'))
const ccsr = () => (_ccsr ??= loadGz<Ccsr>('ccsr.json.gz'))
const pfs = () => (_pfs ??= loadGz<Pfs>('pfs.json.gz'))
const meds = () => (_meds ??= loadGz<Record<string, string>>('meds.json.gz'))

const undot = (c: string) => c.replace('.', '').toUpperCase()
export const dotted = (c: string) => {
  const u = undot(c)
  return u.length > 3 ? `${u.slice(0, 3)}.${u.slice(3)}` : u
}

// ── ICD 10 CM tabular ────────────────────────────────────────────────────────
export interface IcdInfo {
  code: string // dotted display form
  description: string
  billable: boolean
}

export function icdInfo(code: string): IcdInfo | null {
  const hit = tab()[undot(code)]
  return hit ? { code: dotted(code), description: hit[1], billable: hit[0] === 1 } : null
}

// ── Alphabetic index token search ────────────────────────────────────────────
// The official index writes inverted phrases ("Failure, heart"), so candidate
// lookup is token overlap: find index terms containing every query token and
// rank by how few extra tokens they carry.

const STOP = new Set(['the', 'a', 'an', 'of', 'and', 'or', 'with', 'without', 'in', 'to', 'nos', 'nec'])

function tokens(s: string): string[] {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9 ]+/g, ' ')
    .split(/\s+/)
    // Keep single digits (type 2, stage 3) so the reranker can distinguish
    // diabetes types and CKD stages; drop other single characters and stopwords.
    .filter((t) => (t.length > 1 || /^\d$/.test(t)) && !STOP.has(t))
}

function ensureTokenIndex() {
  if (_tokenIndex) return
  const raw = loadGz<IcdIndex>('icd10index.json.gz')
  _terms = Object.entries(raw).map(([term, codes]) => ({ term, codes }))
  _tokenIndex = new Map()
  _terms.forEach(({ term }, i) => {
    for (const t of new Set(tokens(term))) {
      const arr = _tokenIndex!.get(t)
      if (arr) arr.push(i)
      else _tokenIndex!.set(t, [i])
    }
  })
}

export interface IcdCandidate extends IcdInfo {
  indexTerm: string // the official index term that produced this candidate
  overlap: number // query tokens covered by the index term (reranker feature)
  termLen: number // index term length in tokens (reranker feature)
  rank: number // retrieval position (reranker feature)
}

// Common clinical abbreviations and shorthand expanded to the wording used in
// the official ICD 10 CM index. These are standard medical abbreviations, not
// invented content; they only widen the search so an entity like "COPD" or
// "UTI" reaches the same codes the spelled out phrase would.
const ABBREV: Record<string, string> = {
  copd: 'chronic obstructive pulmonary disease',
  uti: 'urinary tract infection',
  mi: 'myocardial infarction',
  nstemi: 'non st elevation myocardial infarction',
  stemi: 'st elevation myocardial infarction',
  chf: 'congestive heart failure',
  hf: 'heart failure',
  cad: 'coronary artery disease',
  afib: 'atrial fibrillation',
  htn: 'hypertension',
  dm: 'diabetes mellitus',
  t2dm: 'type 2 diabetes mellitus',
  t1dm: 'type 1 diabetes mellitus',
  ckd: 'chronic kidney disease',
  esrd: 'end stage renal disease',
  aki: 'acute kidney injury',
  cva: 'cerebral infarction',
  tia: 'transient cerebral ischemic attack',
  dvt: 'deep vein thrombosis',
  pe: 'pulmonary embolism',
  gerd: 'gastro esophageal reflux',
  copd_exac: 'chronic obstructive pulmonary disease with acute exacerbation',
  gi: 'gastrointestinal',
  sob: 'shortness of breath',
  ams: 'altered mental status',
  osa: 'obstructive sleep apnea',
  bph: 'benign prostatic hyperplasia',
  ra: 'rheumatoid arthritis',
  oa: 'osteoarthritis',
  gout: 'gout',
  copd_abbrev: 'chronic obstructive pulmonary disease',
  mdd: 'major depressive disorder',
  gad: 'generalized anxiety disorder',
  ptsd: 'post traumatic stress disorder',
  adhd: 'attention deficit hyperactivity disorder',
  afib_rvr: 'atrial fibrillation',
  copd_flare: 'chronic obstructive pulmonary disease',
}

// Query words that carry no diagnostic weight on their own, so a single token
// fallback should never anchor on them.
const WEAK = new Set(['acute', 'chronic', 'severe', 'mild', 'moderate', 'left', 'right',
  'bilateral', 'exacerbation', 'disorder', 'disease', 'syndrome', 'productive', 'dry',
  'unspecified', 'history', 'stage', 'type', 'primary', 'secondary', 'possible', 'suspected'])

function expand(phrase: string): string {
  return phrase
    .toLowerCase()
    .split(/\s+/)
    .map((w) => ABBREV[w.replace(/[^a-z0-9]/g, '')] ?? w)
    .join(' ')
}

export function icdCandidates(phrase: string, limit = 8): IcdCandidate[] {
  ensureTokenIndex()
  const q = tokens(expand(phrase))
  if (!q.length) return []
  // Terms containing at least `need` of the query tokens.
  const gather = (toks: string[], need: number): number[] => {
    const counts = new Map<number, number>()
    for (const t of new Set(toks)) {
      for (const id of _tokenIndex!.get(t) ?? []) counts.set(id, (counts.get(id) ?? 0) + 1)
    }
    return [...counts.entries()].filter(([, n]) => n >= need).map(([id]) => id)
  }

  // Back off from "every token" toward the head noun so a phrase like
  // "productive cough" still reaches "cough" and "COPD exacerbation" (expanded)
  // still reaches the COPD codes. Over retrieval is fine: the caller lets Claude
  // pick among candidates with the note as context, or abstain.
  const uniq = [...new Set(q)]
  let ids = gather(uniq, uniq.length)
  if (!ids.length && uniq.length >= 2) ids = gather(uniq, uniq.length - 1)
  if (!ids.length) {
    // Single strong tokens, longest first, skipping weak modifiers.
    const strong = uniq.filter((t) => !WEAK.has(t)).sort((a, b) => b.length - a.length)
    for (const t of strong.length ? strong : uniq) {
      ids = gather([t], 1)
      if (ids.length) break
    }
  }

  const qset = new Set(q)
  const scored = ids
    .map((id) => {
      const { term, codes } = _terms![id]
      const tt = tokens(term)
      const overlap = tt.filter((t) => qset.has(t)).length
      // Head match: the index term leads with a query word (for example the main
      // term "Fever" rather than "Malaria" which merely mentions fever). This
      // keeps the primary meaning of a symptom or disease ranked first.
      const head = tt.length && qset.has(tt[0]) ? 1 : 0
      return { term, codes, overlap, head, extra: tt.length - overlap }
    })
    .sort((a, b) => b.overlap - a.overlap || b.head - a.head || a.extra - b.extra || a.term.length - b.term.length)
  const out: IcdCandidate[] = []
  const seen = new Set<string>()
  for (const s of scored) {
    for (const code of s.codes) {
      const info = tab()[undot(code)]
      if (!info || seen.has(undot(code))) continue
      seen.add(undot(code))
      out.push({
        code: dotted(code),
        description: info[1],
        billable: info[0] === 1,
        indexTerm: s.term,
        overlap: s.overlap,
        termLen: tokens(s.term).length,
        rank: out.length,
      })
      if (out.length >= limit) return out
    }
  }
  return out
}

// ── CCSR clinical categories ─────────────────────────────────────────────────
export function ccsrCategory(code: string): { id: string; label: string } | null {
  const id = ccsr().map[undot(code)]
  return id ? { id, label: ccsr().categories[id] ?? id } : null
}

// ── Fee schedules ────────────────────────────────────────────────────────────
export interface ProcPrice {
  price: number
  schedule: 'PFS' | 'CLFS'
  description?: string // present only for public domain HCPCS Level II codes
}

export function procPrice(code: string): ProcPrice | null {
  const hit = pfs().pay[code.trim().toUpperCase()]
  if (!hit) return null
  return {
    price: hit[0],
    schedule: hit[1] === 'L' ? 'CLFS' : 'PFS',
    description: hit.length > 2 ? (hit[2] as string) : undefined,
  }
}

export const knownProcCode = (code: string) => !!pfs().pay[code.trim().toUpperCase()]
export const pfsConversionFactor = () => pfs().cf

// ── RxNorm medication vocabulary ─────────────────────────────────────────────
export function medMatch(name: string): { name: string; tty: 'IN' | 'BN' } | null {
  const n = name.toLowerCase().trim()
  const hit = meds()[n] ?? meds()[n.replace(/s$/, '')]
  return hit ? { name: n, tty: hit as 'IN' | 'BN' } : null
}

// ── MedlinePlus Connect: consumer language for an ICD 10 code ────────────────
// Free NLM API, called at synthesis time and cached per code for the life of
// the serverless instance. Absence is fine; the patient writer explains the
// condition itself and the UI labels which source produced each explanation.
const _mlp = new Map<string, string | null>()

export async function medlinePlus(code: string): Promise<string | null> {
  const key = dotted(code)
  if (_mlp.has(key)) return _mlp.get(key) ?? null
  try {
    const url =
      'https://connect.medlineplus.gov/service?mainSearchCriteria.v.cs=2.16.840.1.113883.6.90' +
      `&mainSearchCriteria.v.c=${encodeURIComponent(key)}&knowledgeResponseType=application/json`
    const res = await fetch(url, { signal: AbortSignal.timeout(4000) })
    if (!res.ok) throw new Error(String(res.status))
    const data = (await res.json()) as {
      feed?: { entry?: { title?: { _value?: string }; summary?: { _value?: string } }[] }
    }
    const entry = data.feed?.entry?.[0]
    const summary = entry?.summary?._value
    const text = summary
      ? summary.replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim().slice(0, 600)
      : null
    _mlp.set(key, text)
    return text
  } catch {
    _mlp.set(key, null)
    return null
  }
}
